SELECT address 
FROM STUDIO 
WHERE name='MGM'

SELECT birthdate 
FROM MOVIESTAR 
WHERE name='Kim Basinger'

SELECT networth 
FROM MOVIEEXEC 
WHERE networth>10000000


SELECT name 
FROM MOVIESTAR 
WHERE address="Prefect Rd" OR gender="M"

INSERT INTO MOVIESTAR 
VALUES('Zahari Baharov','Gorno Nadolnishte','M','1977-07-07')

DELETE FROM STUDIO 
WHERE address LIKE "%5%"

UPDATE MOVIE 
SET studioname = "Fox" 
WHERE title LIKE "%star%"


SELECT MOVIESTAR.name,MOVIE.TITLE 
FROM STARSIN 
JOIN MOVIESTAR 
ON MOVIESTAR.NAME = STARSIN.STARNAME 
JOIN MOVIE 
ON MOVIE.title=STARSIN.MOVIETITLE 
WHERE title = 'Terms of Endearment' 


SELECT MOVIESTAR.name,MOVIE.TITLE 
FROM STARSIN 
JOIN MOVIESTAR 
ON MOVIESTAR.NAME = STARSIN.STARNAME 
JOIN MOVIE 
ON MOVIE.title=STARSIN.MOVIETITLE 
JOIN STUDIO 
ON STUDIO.NAME=MOVIE.STUDIONAME 
WHERE STUDIO.name='MGM' AND MOVIE.year=1995 


ALTER TABLE STUDIO 
ADD COLUMN president varchar(255)

UPDATE STUDIO 
SET president="Boiko Borisov" 
WHERE name="MGM"


UPDATE STUDIO 
SET president="Rumen Radev" 
WHERE name="USA Entertainm."

SELECT president 
FROM STUDIO 
WHERE STUDIO.name='MGM'